[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c5ca0a34c69c44ed33e38ec7c1d5db24af32aca6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "26843f3ebe851b3375d6922e1214a513c6c1a20e1a15ef362314445edd85b6cc"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "f309e427863f65c8c1fe60ada47985c7b6a8a6ef"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "019a347ebce0773f3315192b323f35c42547313355251488fcd872becd8f778f"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "9895a25b6e0e56ee364cad9cf29e3dee04be4e04"
os = "windows"

    [[LibCURL.download]]
    sha256 = "2255d771245e9db6d85de9398c63c89bda45bc24761b5693745051954517db9b"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.x86_64-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "2b5f6bf4afd4ebbc257280d29b15d3b8efd7b26e"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6440311ccf8250e501273d0aeb782234c2c51407789fd6463d1645d2a2a16f55"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d257cafe00b90a957950f2ec0af75b5a7d20148b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "93eb72ccfacab00495a1e8325a573c959ad0e22b901b66341fda91c5747ee368"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "22d0ffc4af0e235a843f45bf3f6e6c3dec3748d1"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "013391a945045c17415af6971ccc5468e395e80ff78c4020b76f003a0992f8d4"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "fcc314883733c513fbcd6b4ccdea5c0092d82c11"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d23d9e2e19edc0c3a28339c1c8788d81ce6831e018dda49c575f6f0983f4cf09"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ce89f7c428980dafc7bfc06841f7c3f637e92749"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d064e36d18dbff8e39abb3a8ff62c25075f011d3a64ddf1cfc24acd211938a9b"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.22.0+1/LibCURL.v8.22.0.x86_64-apple-darwin.tar.gz"
