[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1a9c0ca3bebe120b7f82dfc6d260bf9fc9f5ba19"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1c1d32cb9f5b4afd4e8e484bb6743a69eef334d2592025b5e1ec7b97213af600"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e2130a2987be8f95358cc5985a064d7dc2e34612"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "11174d2e83a3de3b85de77c5d3975cdc842d1274aa5fd1de501dfc2821633072"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "b1c9e1e1ac06818514950116182b1bef7895ee4f"
os = "windows"

    [[LibCURL.download]]
    sha256 = "24b3aa42524c349407c6e62820b9344a09643fd804450d4b07e99b4e717423a6"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.x86_64-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "cadc8c863b68200e6bb0e521c1632378027407b7"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "20f0f2b6df48466ae8b40d032738858182765e85dfb0410fe350dd7ba10b19b8"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "fd59eba259c673aa1e39756437bbf48e76517065"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a83055759a43e222ee1ab0567ca817243b069a48b002011ee61e3d6d7a0379d8"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "e02a27ff81da41868912b52c5db755102a600f56"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e927ffd5df4c81c9bbdd5d0628aeadfcca7b5d8035fa2c1fbc514b643a5515aa"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "a3dbff37474d41aa07a57f4a13f3a5e56f440efd"
os = "macos"

    [[LibCURL.download]]
    sha256 = "58bdc0337ec07132040d53ef6b588f354f0c39cbdc65de0f97169f15b0fc62a1"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "6d05242b66b3083e3a4889afa70b0a618fc61e6d"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d1f5a31e68825fc53ae3dd85b20f3d1bc286c0493f6d1af3cb5a4a64e72b2935"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.19.0+1/LibCURL.v8.19.0.x86_64-apple-darwin.tar.gz"
