name: Build Job

on:
  push:
    branches: [ main, github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh
